
# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_card
    username: postgres
    password: admin

  # JPA properties
  jpa:
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: validate
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true

  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

  # Rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true       # Enable retry logic
          max-attempts: 5     # Maximum number of retry attempts
          initial-interval: 3s  # Initial retry interval in milliseconds
          multiplier: 1     # Multiplier to increase retry interval
          max-interval: 5s  # Maximum retry interval in milliseconds
        missing-queues-fatal: false
    #        acknowledge-mode: auto # Auto acknowledgment of messages

#Rabbit
rabbitmq:
  queue:
    person: PERSON_Q
    person-dlq: PERSON_DLQ

# Port
server:
  port: 8081
